"""users table

Revision ID: 926069e20420
Revises: 
Create Date: 2020-05-07 14:16:27.805954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926069e20420'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('phonenumber', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.Column('propertyaddress', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_notes'), 'user', ['notes'], unique=False)
    op.create_index(op.f('ix_user_phonenumber'), 'user', ['phonenumber'], unique=False)
    op.create_index(op.f('ix_user_propertyaddress'), 'user', ['propertyaddress'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_propertyaddress'), table_name='user')
    op.drop_index(op.f('ix_user_phonenumber'), table_name='user')
    op.drop_index(op.f('ix_user_notes'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
